FROM bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list

RUN echo "deb http://archive.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list

RUN apt update -y && apt upgrade -y

RUN apt install python -y

WORKDIR /tools

COPY ./tools .

RUN chmod +x ./script.sh

CMD [ "./script.sh" ]
